version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--bind", "cache", "--port", "6379"]
    volumes: 
      - cache:/data
  api:
    container_name: deskpass
    build: .
    depends_on:
      - cache
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      REDIS_HOST: cache
      REDIS_PORT: 6379
    links:
      - cache
    volumes:
      - ./:/src
volumes:
  cache:
    driver: local